name: CodeQL Analysis

on:
  push:
    branches: [master]  # Run on pushes to the main branch

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [javascript,typescript]  # Add more languages as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Analyze
      uses: github/codeql-action/analyze@v3
    - name: Upload CodeQL results
      uses: actions/upload-artifact@v3
      with:
        name: codeql-results
        path: .codeql-results
