name: CodeQL Analysis

on:
  push:
    branches: [master]  # Run on pushes to the main branch

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [typescript]  # Add more languages as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Analyze
      uses: github/codeql-action/analyze@v3
    - name: Test
      run: ng test
    - name: Create CodeQL results directory
      run: mkdir .codeql-results

      # Example: Copy some files into .codeql-results directory
    - name: Copy CodeQL results
      run: cp codeql-results/* .codeql-results/
      
    - name: Upload CodeQL results
      uses: actions/upload-artifact@v3
      with:
        name: codeql-results
        path: ${{github.workspace}}/.codeql-results
